# Generated by Django 6.0.2 on 2026-02-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_by', models.CharField(choices=[('date', 'Date'), ('popularity', 'Popularity')], default='date', max_length=20)),
                ('therapists_only', models.BooleanField(default=False)),
                ('keyword_filter', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
